CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    seller_id BIGINT NOT NULL,

    name VARCHAR(150) NOT NULL,

    description VARCHAR(1000),

    price DECIMAL(10,2) NOT NULL,

    stock_quantity INT NOT NULL,

    category VARCHAR(100) NOT NULL,

    image_url VARCHAR(500),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_products_seller
        FOREIGN KEY (seller_id)
        REFERENCES users(id),

    CONSTRAINT chk_products_price
        CHECK (price >= 0),

    CONSTRAINT chk_products_stock
        CHECK (stock_quantity >= 0)
);
CREATE INDEX idx_products_seller_id
ON products(seller_id);
CREATE INDEX idx_products_category
ON products(category);