-- ========================================================
-- V7: E-COMMERCE ENHANCEMENTS (STAGE 2)
-- Addresses, Wishlist, and Reviews flexibility
-- ========================================================

-- 1. SAVED DELIVERY ADDRESSES
CREATE TABLE IF NOT EXISTS addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    address_line VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_addresses_user_id ON addresses(user_id);


-- 2. WISHLIST ITEMS
CREATE TABLE IF NOT EXISTS wishlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wishlist_buyer FOREIGN KEY (buyer_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_wishlist_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT uq_wishlist_buyer_product UNIQUE (buyer_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_wishlist_buyer_id ON wishlist_items(buyer_id);


-- 3. REVIEWS FLEXIBILITY
-- Allow customer product reviews from product detail page without strict order_id constraint
ALTER TABLE reviews ALTER COLUMN order_id DROP NOT NULL;
