-- ========================================================
-- V8: E-COMMERCE FLIPKART ENHANCEMENTS
-- Profile fields, Enhanced Orders & Tracking, Coupons & Offers, Password Reset
-- ========================================================

-- 1. ADD PHONE TO USERS TABLE
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(20);

-- 2. ENHANCE ORDERS TABLE
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50) DEFAULT 'COD';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) DEFAULT 'PENDING';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_status VARCHAR(50) DEFAULT 'PLACED';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_address VARCHAR(500);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS coupon_code VARCHAR(50);

-- 3. COUPONS & DISCOUNTS TABLE
CREATE TABLE IF NOT EXISTS coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    discount_type VARCHAR(20) NOT NULL, -- 'PERCENTAGE' or 'FLAT'
    discount_value DECIMAL(10,2) NOT NULL,
    min_order_value DECIMAL(10,2) DEFAULT 0.00,
    max_discount DECIMAL(10,2) DEFAULT 0.00,
    valid_until TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_coupons_code ON coupons(code);

-- Seed Initial Coupons (Using MERGE to avoid duplicate inserts on re-runs)
MERGE INTO coupons (code, discount_type, discount_value, min_order_value, max_discount, is_active)
KEY (code)
VALUES
    ('FIRST50', 'PERCENTAGE', 50.00, 200.00, 150.00, TRUE),
    ('NITHYA100', 'FLAT', 100.00, 500.00, 100.00, TRUE),
    ('FESTIVE20', 'PERCENTAGE', 20.00, 1000.00, 500.00, TRUE),
    ('SAVE10', 'PERCENTAGE', 10.00, 300.00, 200.00, TRUE);

-- 4. PASSWORD RESET TOKENS TABLE
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    token VARCHAR(100) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    expiry_time TIMESTAMP NOT NULL,
    used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pwd_reset_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pwd_reset_user ON password_reset_tokens(user_id);
